name: Atualizar Biblioteca

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0' # roda todo domingo às 12h

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # versão LTS estável

      - name: Instalar dependências
        run: npm install

      - name: Atualizar catálogo
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          SHEET_ID: ${{ secrets.SHEET_ID }} # se o generate.js também usa o ID da planilha
        run: node generate.js

      - name: Commit automático
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add games.json
          git diff --cached --quiet || git commit -m "Atualização automática da biblioteca"
          git push
