name: Atualizar Biblioteca

permissions:
  contents: write

on:

  schedule:
    - cron: '0 12 * * 0'

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Executar geração
        env:
        console.log("CLIENT_ID:", !!process.env.TWITCH_CLIENT_ID);
        console.log("CLIENT_SECRET:", !!process.env.TWITCH_CLIENT_SECRET);
        run: node generate.js

      - name: Commit automático
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Atualização automática da biblioteca"

          git push
