name: Atualizar Biblioteca

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Atualizar catálogo
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          echo "TWITCH_CLIENT_ID recebido: $TWITCH_CLIENT_ID"
          echo "TWITCH_CLIENT_SECRET recebido: $TWITCH_CLIENT_SECRET"
          node generate.js

          - name: Commit automático
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add games-3.json
          git commit -m "Atualização automática da biblioteca" || echo "Nenhuma alteração para commitar"
          git push origin main
